# Generated by Django 3.2 on 2023-10-28 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20231028_1530'),
        ('reviews', '0002_review'),
    ]

    operations = [
    ]
